-- Calling function info
-- Generated by the SimpleSpy V3 serializer

local functionInfo = {
    ["upvalues"] = {
        [1] = {
            ["can_equip_server"] = function can_equip_server() end -- Function Called: can_equip_server,
            ["display_fail_message"] = function display_fail_message() end -- Function Called: display_fail_message,
            ["init"] = function init() end -- Function Called: init,
            ["can_unequip_server"] = function can_unequip_server() end -- Function Called: can_unequip_server,
            ["can_equip_client"] = function can_equip_client() end -- Function Called: can_equip_client,
            ["can_unequip_client"] = function can_unequip_client() end -- Function Called: can_unequip_client
        },
        [2] = {
            ["tokens"] = 14,
            ["requests_per_second"] = 1,
            ["timestamp"] = 1783412355.688977,
            ["max_tokens"] = 15,
            ["reserved_tokens"] = 0
        },
        [3] = 0,
        [4] = function predict_equip() end -- Function Called: predict_equip,
        [5] = {
            ["get"] = function get() end -- Function Called: get,
            ["get_event"] = function get_event() end -- Function Called: get_event,
            ["init"] = function init() end -- Function Called: init
        },
        [6] = {
            ["register_callback_plus_existing"] = function register_callback_plus_existing() end -- Function Called: register_callback_plus_existing,
            ["register_server_on_change_hook"] = function register_server_on_change_hook() end -- Function Called: register_server_on_change_hook,
            ["register_callback"] = function register_callback() end -- Function Called: register_callback,
            ["update"] = function update() end -- Function Called: update,
            ["register_server_constant_on_change_hook"] = function register_server_constant_on_change_hook() end -- Function Called: register_server_constant_on_change_hook,
            ["get_data"] = function get_data() end -- Function Called: get_data,
            ["get_server_latest"] = function get_server_latest() end -- Function Called: get_server_latest,
            ["get_server"] = function get_server() end -- Function Called: get_server,
            ["DataChangedEvent"] = {
                ["_handlerListHead"] = {
                    ["_fn"] = function: 0x0f9d261f0a218aa1,
                    ["_connected"] = true,
                    ["_signal"] = {} --[[DUPLICATE]],
                    ["_next"] = false
                }
            },
            ["server_dequeue"] = function server_dequeue() end -- Function Called: server_dequeue,
            ["init"] = function init() end -- Function Called: init,
            ["rollback_prediction"] = function rollback_prediction() end -- Function Called: rollback_prediction,
            ["predict"] = function predict() end -- Function Called: predict,
            ["get_server_constant"] = function get_server_constant() end -- Function Called: get_server_constant,
            ["update_server"] = function update_server() end -- Function Called: update_server,
            ["predict_update_server"] = function predict_update_server() end -- Function Called: predict_update_server,
            ["get"] = function get() end -- Function Called: get
        }
    },
    ["info"] = {
        ["source"] = "=ReplicatedStorage.ClientModules.Game.ClientToolManager",
        ["what"] = "Lua",
        ["numparams"] = 2,
        ["func"] = function equip() end -- Function Called: equip,
        ["short_src"] = "ReplicatedStorage.ClientModules.Game.ClientToolManager",
        ["currentline"] = 151,
        ["name"] = "equip",
        ["is_vararg"] = 0,
        ["nups"] = 6
    },
    ["advancedinfo"] = {
        ["DebugId"] = {
            ["SourceScriptDebugId"] = "1_231243",
            ["RemoteDebugId"] = "1_629027",
            ["CallingScriptDebugId"] = "1_231225"
        },
        ["OnClientInvoke"] = "N/A",
        ["Metamethod"] = "__namecall",
        ["Protos"] = {}
    },
    ["script"] = {
        ["SourceScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientModules"):WaitForChild("Game"):WaitForChild("ClientToolManager"),
        ["CallingScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientModules"):WaitForChild("Core"):WaitForChild("UIManager"):WaitForChild("UIManager")
    },
    ["constants"] = {
        [1] = "can_equip_client",
        [2] = "reserve_fill",
        [3] = "action",
        [4] = "equip",
        [5] = "is_server",
        [6] = false,
        [7] = "message",
        [8] = "You are equipping items too quickly!",
        [9] = "message_type",
        [10] = "Hint",
        [12] = 0,
        [13] = "category",
        [14] = 1,
        [15] = "get",
        [16] = "ToolAPI/Equip",
        [17] = "unique",
        [18] = "InvokeServer",
        [19] = "rollback_prediction",
        [20] = "equip_manager"
    }
}

functionInfo.upvalues[6].DataChangedEvent._handlerListHead._signal = functionInfo.upvalues[6].DataChangedEvent

-- Calling function info
-- Generated by the SimpleSpy V3 serializer

function getNil(name,class) for _,v in next, getnilinstances() do if v.ClassName==class and v.Name==name then return v;end end end

local functionInfo = {
    ["upvalues"] = {
        [1] = {
            ["get"] = function get() end -- Function Called: get,
            ["get_event"] = function get_event() end -- Function Called: get_event,
            ["init"] = function init() end -- Function Called: init
        },
        [2] = {
            ["track"] = getNil("PhoenixHold", "AnimationTrack"),
            ["tool_use_end_callback"] = function: 0x560fa1d15b1cff61,
            ["entry"] = {
                ["placeable_type"] = "magic_house_door",
                ["anims"] = {
                    ["hold"] = "PhoenixHold"
                },
                ["model_handle"] = "MagicHouseDoor",
                ["typechecked"] = true,
                ["id"] = "magic_house_door",
                ["image"] = "rbxassetid://4661940658",
                ["name"] = "Magic House Door",
                ["category"] = "toys",
                ["rarity"] = "ultra_rare",
                ["kind"] = "magic_house_door",
                ["contentpack"] = "Vanilla",
                ["tool"] = "PlaceableTool"
            },
            ["destroyed"] = true,
            ["in_use"] = false,
            ["unequipped_signal"] = {
                ["_handlerListHead"] = false
            },
            ["tool_entry"] = {
                ["client_use"] = function client_use() end -- Function Called: client_use,
                ["equipped"] = function equipped() end -- Function Called: equipped,
                ["server_render"] = function server_render() end -- Function Called: server_render
            },
            ["can_place"] = function: 0xc8433c64f5da4f31,
            ["last_use_time"] = 89.7328381949992,
            ["item_data"] = {
                ["unique"] = "2_857ba6dd96824623babdca65a30cce68",
                ["category"] = "toys",
                ["id"] = "magic_house_door",
                ["kind"] = "magic_house_door",
                ["properties"] = {},
                ["newness_order"] = 0
            },
            ["get_placement_cf"] = function: 0x778fd15601d5a9e1,
            ["tool"] = getNil("PlaceableTool", "Tool"),
            ["tool_use_start_callback"] = function: 0xe4f8bb56a735f2a1
        }
    },
    ["info"] = {
        ["source"] = "=ReplicatedStorage.ClientModules.Game.ToolWrapper",
        ["what"] = "Lua",
        ["numparams"] = 0,
        ["func"] = function: 0x6cb7d29950eb1aa1,
        ["short_src"] = "ReplicatedStorage.ClientModules.Game.ToolWrapper",
        ["currentline"] = 240,
        ["name"] = "",
        ["is_vararg"] = 0,
        ["nups"] = 2
    },
    ["advancedinfo"] = {
        ["DebugId"] = {
            ["SourceScriptDebugId"] = "1_231505",
            ["RemoteDebugId"] = "1_629028",
            ["CallingScriptDebugId"] = "1_231562"
        },
        ["OnClientInvoke"] = "N/A",
        ["Metamethod"] = "__namecall",
        ["Protos"] = {}
    },
    ["script"] = {
        ["SourceScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientModules"):WaitForChild("Game"):WaitForChild("ToolWrapper"),
        ["CallingScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientModules"):WaitForChild("Utilities"):WaitForChild("ClickTapInWorldExclusionList")
    },
    ["constants"] = {
        [1] = "get",
        [2] = "ToolAPI/ServerUseTool",
        [3] = "item_data",
        [4] = "unique",
        [5] = "START",
        [6] = "InvokeServer"
    }
}


-- Calling function info
-- Generated by the SimpleSpy V3 serializer

local functionInfo = {
    ["upvalues"] = {
        [1] = function load() end -- Function Called: load,
        [2] = {
            ["await_table_instances_by_id_shallow"] = function await_table_instances_by_id_shallow() end -- Function Called: await_table_instances_by_id_shallow,
            ["remove_streaming_id"] = function remove_streaming_id() end -- Function Called: remove_streaming_id,
            ["as_id_recursive_mut"] = function as_id_recursive_mut() end -- Function Called: as_id_recursive_mut,
            ["cancel_descendant_count"] = function cancel_descendant_count() end -- Function Called: cancel_descendant_count,
            ["await_matching_descendant_count"] = function await_matching_descendant_count() end -- Function Called: await_matching_descendant_count,
            ["check_for_bad_instances"] = function check_for_bad_instances() end -- Function Called: check_for_bad_instances,
            ["assign_or_get_streaming_ids_for_table"] = function assign_or_get_streaming_ids_for_table() end -- Function Called: assign_or_get_streaming_ids_for_table,
            ["set_model_streaming_mode_recursive"] = function set_model_streaming_mode_recursive() end -- Function Called: set_model_streaming_mode_recursive,
            ["is_streaming_id"] = function is_streaming_id() end -- Function Called: is_streaming_id,
            ["assign_new_streaming_id"] = function assign_new_streaming_id() end -- Function Called: assign_new_streaming_id,
            ["get_instance_by_id"] = function get_instance_by_id() end -- Function Called: get_instance_by_id,
            ["promise_await_instance_by_id"] = function promise_await_instance_by_id() end -- Function Called: promise_await_instance_by_id,
            ["assign_or_get_streaming_id"] = function assign_or_get_streaming_id() end -- Function Called: assign_or_get_streaming_id,
            ["await_instance_by_id"] = function await_instance_by_id() end -- Function Called: await_instance_by_id,
            ["await_many_instances_by_id"] = function await_many_instances_by_id() end -- Function Called: await_many_instances_by_id,
            ["as_id"] = function assign_or_get_streaming_id() end -- Function Called: assign_or_get_streaming_id,
            ["await_table_shallow"] = function await_table_instances_by_id_shallow() end -- Function Called: await_table_instances_by_id_shallow,
            ["keep_on_fallen_parts"] = function keep_on_fallen_parts() end -- Function Called: keep_on_fallen_parts,
            ["nil_on_missing_descenants"] = function nil_on_missing_descenants() end -- Function Called: nil_on_missing_descenants,
            ["does_descendant_count_match"] = function does_descendant_count_match() end -- Function Called: does_descendant_count_match,
            ["await_recursive_mut"] = function await_recursive_mut() end -- Function Called: await_recursive_mut,
            ["await_many"] = function await_many_instances_by_id() end -- Function Called: await_many_instances_by_id,
            ["as_id_recursive_clone"] = function as_id_recursive_clone() end -- Function Called: as_id_recursive_clone,
            ["on_item_streamed"] = function on_item_streamed() end -- Function Called: on_item_streamed,
            ["get_streaming_id"] = function get_streaming_id() end -- Function Called: get_streaming_id,
            ["as_id_table"] = function assign_or_get_streaming_ids_for_table() end -- Function Called: assign_or_get_streaming_ids_for_table,
            ["await"] = function await_instance_by_id() end -- Function Called: await_instance_by_id,
            ["attach_descendant_count"] = function attach_descendant_count() end -- Function Called: attach_descendant_count,
            ["get"] = function get_instance_by_id() end -- Function Called: get_instance_by_id
        },
        [3] = {
            ["_new"] = function _new() end -- Function Called: _new,
            ["_all"] = function _all() end -- Function Called: _all,
            ["_try"] = function _try() end -- Function Called: _try,
            ["__tostring"] = function __tostring() end -- Function Called: __tostring,
            ["defer"] = function defer() end -- Function Called: defer,
            ["race"] = function race() end -- Function Called: race,
            ["some"] = function some() end -- Function Called: some,
            ["Error"] = {
                ["new"] = function new() end -- Function Called: new,
                ["__index"] = {} --[[DUPLICATE]],
                ["Kind"] = {
                    ["ExecutionError"] = "ExecutionError",
                    ["AlreadyCancelled"] = "AlreadyCancelled",
                    ["TimedOut"] = "TimedOut",
                    ["NotResolvedInTime"] = "NotResolvedInTime"
                },
                ["is"] = function is() end -- Function Called: is,
                ["extend"] = function extend() end -- Function Called: extend,
                ["isKind"] = function isKind() end -- Function Called: isKind,
                ["__tostring"] = function __tostring() end -- Function Called: __tostring,
                ["getErrorChain"] = function getErrorChain() end -- Function Called: getErrorChain
            },
            ["_getTime"] = function clock() end -- Function Called: clock,
            ["promisify"] = function promisify() end -- Function Called: promisify,
            ["__index"] = {
                ["andThenCall"] = function andThenCall() end -- Function Called: andThenCall,
                ["finally"] = function finally() end -- Function Called: finally,
                ["_andThen"] = function _andThen() end -- Function Called: _andThen,
                ["andThenReturn"] = function andThenReturn() end -- Function Called: andThenReturn,
                ["finallyReturn"] = function finallyReturn() end -- Function Called: finallyReturn,
                ["_reject"] = function _reject() end -- Function Called: _reject,
                ["_finally"] = function _finally() end -- Function Called: _finally,
                ["await"] = function await() end -- Function Called: await,
                ["finallyCall"] = function finallyCall() end -- Function Called: finallyCall,
                ["getStatus"] = function getStatus() end -- Function Called: getStatus,
                ["timeout"] = function timeout() end -- Function Called: timeout,
                ["cancel"] = function cancel() end -- Function Called: cancel,
                ["_unwrap"] = function _unwrap() end -- Function Called: _unwrap,
                ["_consumerCancelled"] = function _consumerCancelled() end -- Function Called: _consumerCancelled,
                ["andThen"] = function andThen() end -- Function Called: andThen,
                ["doneCall"] = function doneCall() end -- Function Called: doneCall,
                ["expect"] = function expect() end -- Function Called: expect,
                ["done"] = function done() end -- Function Called: done,
                ["awaitValue"] = function expect() end -- Function Called: expect,
                ["catch"] = function catch() end -- Function Called: catch,
                ["now"] = function now() end -- Function Called: now,
                ["tap"] = function tap() end -- Function Called: tap,
                ["_resolve"] = function _resolve() end -- Function Called: _resolve,
                ["awaitStatus"] = function awaitStatus() end -- Function Called: awaitStatus,
                ["_finalize"] = function _finalize() end -- Function Called: _finalize,
                ["doneReturn"] = function doneReturn() end -- Function Called: doneReturn
            },
            ["new"] = function new() end -- Function Called: new,
            ["resolve"] = function resolve() end -- Function Called: resolve,
            ["retry"] = function retry() end -- Function Called: retry,
            ["try"] = function try() end -- Function Called: try,
            ["_timeEvent"] = RBXScriptSignal --[[RBXScriptSignal's are not supported]],
            ["prototype"] = {} --[[DUPLICATE]],
            ["async"] = function defer() end -- Function Called: defer,
            ["fold"] = function fold() end -- Function Called: fold,
            ["Status"] = {
                ["Started"] = "Started",
                ["Cancelled"] = "Cancelled",
                ["Rejected"] = "Rejected",
                ["Resolved"] = "Resolved"
            },
            ["any"] = function any() end -- Function Called: any,
            ["reject"] = function reject() end -- Function Called: reject,
            ["allSettled"] = function allSettled() end -- Function Called: allSettled,
            ["each"] = function each() end -- Function Called: each,
            ["is"] = function is() end -- Function Called: is,
            ["all"] = function all() end -- Function Called: all,
            ["delay"] = function delay() end -- Function Called: delay,
            ["fromEvent"] = function fromEvent() end -- Function Called: fromEvent
        },
        [4] = game:GetService("CollectionService")
    },
    ["info"] = {
        ["source"] = "=ReplicatedStorage.ClientDB.ToolDB",
        ["what"] = "Lua",
        ["numparams"] = 3,
        ["func"] = function client_use() end -- Function Called: client_use,
        ["short_src"] = "ReplicatedStorage.ClientDB.ToolDB",
        ["currentline"] = 1422,
        ["name"] = "client_use",
        ["is_vararg"] = 0,
        ["nups"] = 4
    },
    ["advancedinfo"] = {
        ["DebugId"] = {
            ["SourceScriptDebugId"] = "1_230954",
            ["RemoteDebugId"] = "1_629136",
            ["CallingScriptDebugId"] = "1_231562"
        },
        ["OnClientInvoke"] = "N/A",
        ["Metamethod"] = "__namecall",
        ["Protos"] = {
            [1] = function: 0x33ff675222628f41
        }
    },
    ["script"] = {
        ["SourceScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientDB"):WaitForChild("ToolDB"),
        ["CallingScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientModules"):WaitForChild("Utilities"):WaitForChild("ClickTapInWorldExclusionList")
    },
    ["constants"] = {
        [1] = "RouterClient",
        [2] = "UIManager",
        [3] = "PlaceableToolHelper",
        [4] = "game",
        [5] = game,
        [6] = "Players",
        [7] = "LocalPlayer",
        [8] = "Character",
        [9] = "HumanoidRootPart",
        [10] = "FindFirstChild",
        [11] = "can_place",
        [12] = "validate_placement",
        [13] = "placeable_type",
        [14] = "toy_furniture",
        [15] = "get",
        [16] = "ToolAPI/PlaceToyFurniture",
        [17] = "get_placement_cf",
        [18] = "InvokeServer",
        [19] = "PlaceableToolAPI/CreatePlaceable",
        [20] = "await",
        [21] = "apps",
        [22] = "SpecialEffectsApp",
        [23] = "PlacementBlock",
        [24] = "WaitForChild",
        [25] = "placement_effect",
        [26] = "placeable_furniture",
        [27] = "fromEvent",
        [28] = "kind",
        [29] = "GetInstanceAddedSignal",
        [30] = "andThen"
    }
}

functionInfo.upvalues[3].Error.__index = functionInfo.upvalues[3].Error
functionInfo.upvalues[3].prototype = functionInfo.upvalues[3].__index

-- Calling function info
-- Generated by the SimpleSpy V3 serializer

function getNil(name,class) for _,v in next, getnilinstances() do if v.ClassName==class and v.Name==name then return v;end end end

local functionInfo = {
    ["upvalues"] = {
        [1] = {
            ["get"] = function get() end -- Function Called: get,
            ["get_event"] = function get_event() end -- Function Called: get_event,
            ["init"] = function init() end -- Function Called: init
        },
        [2] = {
            ["track"] = getNil("PhoenixHold", "AnimationTrack"),
            ["tool_use_end_callback"] = function: 0x560fa1d15b1cff61,
            ["entry"] = {
                ["placeable_type"] = "magic_house_door",
                ["anims"] = {
                    ["hold"] = "PhoenixHold"
                },
                ["model_handle"] = "MagicHouseDoor",
                ["typechecked"] = true,
                ["id"] = "magic_house_door",
                ["image"] = "rbxassetid://4661940658",
                ["name"] = "Magic House Door",
                ["category"] = "toys",
                ["rarity"] = "ultra_rare",
                ["kind"] = "magic_house_door",
                ["contentpack"] = "Vanilla",
                ["tool"] = "PlaceableTool"
            },
            ["destroyed"] = true,
            ["in_use"] = false,
            ["unequipped_signal"] = {
                ["_handlerListHead"] = false
            },
            ["tool_entry"] = {
                ["client_use"] = function client_use() end -- Function Called: client_use,
                ["equipped"] = function equipped() end -- Function Called: equipped,
                ["server_render"] = function server_render() end -- Function Called: server_render
            },
            ["can_place"] = function: 0xc8433c64f5da4f31,
            ["last_use_time"] = 89.7328381949992,
            ["item_data"] = {
                ["unique"] = "2_857ba6dd96824623babdca65a30cce68",
                ["category"] = "toys",
                ["id"] = "magic_house_door",
                ["kind"] = "magic_house_door",
                ["properties"] = {},
                ["newness_order"] = 0
            },
            ["get_placement_cf"] = function: 0x778fd15601d5a9e1,
            ["tool"] = getNil("PlaceableTool", "Tool"),
            ["tool_use_start_callback"] = function: 0xe4f8bb56a735f2a1
        }
    },
    ["info"] = {
        ["source"] = "=ReplicatedStorage.ClientModules.Game.ToolWrapper",
        ["what"] = "Lua",
        ["numparams"] = 0,
        ["func"] = function: 0x0c56584456b061e1,
        ["short_src"] = "ReplicatedStorage.ClientModules.Game.ToolWrapper",
        ["currentline"] = 226,
        ["name"] = "",
        ["is_vararg"] = 0,
        ["nups"] = 3
    },
    ["advancedinfo"] = {
        ["DebugId"] = {
            ["SourceScriptDebugId"] = "1_231505",
            ["RemoteDebugId"] = "1_629028",
            ["CallingScriptDebugId"] = "1_231562"
        },
        ["OnClientInvoke"] = "N/A",
        ["Metamethod"] = "__namecall",
        ["Protos"] = {}
    },
    ["script"] = {
        ["SourceScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientModules"):WaitForChild("Game"):WaitForChild("ToolWrapper"),
        ["CallingScript"] = game:GetService("ReplicatedStorage"):WaitForChild("ClientModules"):WaitForChild("Utilities"):WaitForChild("ClickTapInWorldExclusionList")
    },
    ["constants"] = {
        [1] = "get",
        [2] = "ToolAPI/ServerUseTool",
        [3] = "item_data",
        [4] = "unique",
        [5] = "END",
        [6] = "InvokeServer"
    }
}

